# CLK mapped to 100MHz clock source
set_property PACKAGE_PIN Y9 [get_ports {GCLK}]
set_property IOSTANDARD LVCMOS18 [get_ports {GCLK}]
# RST mapped to south button (BTNL)
set_property PACKAGE_PIN N15 [get_ports {B_RST}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_RST}]
# INPUTS[5:0] mapped to switches 5:0
set_property PACKAGE_PIN F22 [get_ports {INPUTS[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {INPUTS[0]}]
set_property PACKAGE_PIN G22 [get_ports {INPUTS[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {INPUTS[1]}]
set_property PACKAGE_PIN H22 [get_ports {INPUTS[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {INPUTS[2]}]
set_property PACKAGE_PIN F21 [get_ports {INPUTS[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {INPUTS[3]}]
set_property PACKAGE_PIN H19 [get_ports {INPUTS[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {INPUTS[4]}]
set_property PACKAGE_PIN H18 [get_ports {INPUTS[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {INPUTS[5]}]
# TEST mode button mapped to centre button (BTNC)
set_property PACKAGE_PIN P16 [get_ports {B_TEST}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_TEST}]
# Fault selection (B_F[1:0]) mapped to switches [7:6]  
set_property PACKAGE_PIN H17 [get_ports {B_F[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_F[0]}]
set_property PACKAGE_PIN M15 [get_ports {B_F[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B_F[1]}]
# L_OUT mapped to LED0
set_property PACKAGE_PIN T22 [get_ports {L_OUT}]
set_property IOSTANDARD LVCMOS18 [get_ports {L_OUT}]
# L_ERR mapped to LED2
set_property PACKAGE_PIN U22 [get_ports {L_ERR}]
set_property IOSTANDARD LVCMOS18 [get_ports {L_ERR}]
# L_ID[3:0] mapped to LED 7:4
set_property PACKAGE_PIN V22 [get_ports {L_ID[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {L_ID[0]}]
set_property PACKAGE_PIN W22 [get_ports {L_ID[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {L_ID[1]}]
set_property PACKAGE_PIN U19 [get_ports {L_ID[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {L_ID[2]}]
set_property PACKAGE_PIN U14 [get_ports {L_ID[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {L_ID[3]}]
