webtalk_init -webtalk_dir H:/Documents/Digital Engineering GitHub/DigitalEngineering2023/DE_Project_T3/DE_Project_T3.sim/sim_1/behav/xsim/xsim.dir/TOP_LEVEL_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 16 18:33:20 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174238993_177724661_210718143_320" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b6952711-cce3-4578-8dc9-0421a0e27854" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d7bae909fdc84e26973593db885c9931" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "75" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "210 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14904_KB" -context "xsim\\usage"
webtalk_transmit -clientid 254367727 -regid "174238993_177724661_210718143_320" -xml H:/Documents/Digital Engineering GitHub/DigitalEngineering2023/DE_Project_T3/DE_Project_T3.sim/sim_1/behav/xsim/xsim.dir/TOP_LEVEL_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html H:/Documents/Digital Engineering GitHub/DigitalEngineering2023/DE_Project_T3/DE_Project_T3.sim/sim_1/behav/xsim/xsim.dir/TOP_LEVEL_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm H:/Documents/Digital Engineering GitHub/DigitalEngineering2023/DE_Project_T3/DE_Project_T3.sim/sim_1/behav/xsim/xsim.dir/TOP_LEVEL_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
