@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Feb 23 16:00:36 +0000 2023
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim bist_tb_behav -key {Behavioral:sim_1:Functional:bist_tb} -tclbatch bist_tb.tcl -view C:/Users/Sid/Documents/GitHub/DigitalEngineering2023/DE_Lab4_C/DE_Lab4_C.srcs/sim_1/imports/DE_Lab4/bist_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
